source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JBLoginView_Example', :exclusive => true do
  pod "JBLoginView", :path => "../"
  pod "VISPER"#, :path => "../../VISPER/"
  pod "VISPER-CommandBus"#, :path => "../../VISPER-CommandBus/"
  pod "UIColor-HTMLColors"
end

target 'JBLoginView_Tests', :exclusive => true do
  pod "JBLoginView", :path => "../"
  pod "UIColor-HTMLColors"
end
